spring.application.name=FraudTransactionApp
spring.profiles.active=dev

spring.jackson.default-property-inclusion=non_null

logging.level.com.interswitch.fraudtransactionapp.client=INFO

spring.jackson.deserialization.fail-on-unknown-properties=false

debug=true
logging.level.org.flywaydb=DEBUG